name: Add PDF url to manuscript

on:
  workflow_dispatch:
    inputs:
      msid:
        required: true
        description: Manuscript ID
      versionManuscript:
        description: Manuscript version
      urlPdf:
        description: PDF location (url)

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BRANCH_NAME: "pdfurl-${{ github.event.inputs.msid }}-v${{ github.event.inputs.versionManuscript || 1 }}"

jobs:
  add-pdf-to-manuscript:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: yarn
      - name: yarn install
        run: yarn
      - name: Prepare manuscripts.json with PDF url
        run: |
          cat manuscripts.json | \
            yarn add-pdf-url-to-manuscript \
            --msid "${{ github.event.inputs.msid }}" \
            --versionManuscript "${{ github.event.inputs.versionManuscript || 1 }}" \
            --urlPdf "${{ github.event.inputs.urlPdf }}" | \
            tee manuscripts-new.json > /dev/null
      - name: Replace manuscripts.json
        run: |
          mv manuscripts-new.json manuscripts.json
      - name: Create Pull Request (master)
        if: github.ref == 'refs/heads/master'
        uses: peter-evans/create-pull-request@v5
        with:
          draft: true
          branch: "${{ env.BRANCH_NAME }}"
          branch-suffix: short-commit-hash
          commit-message: "Add pdf url to manuscript ${{ github.event.inputs.msid }}v${{ github.event.inputs.versionManuscript || 1 }} using workflow"
          committer: GitHub Actions <action@github.com>
          title: "Add pdf url to manuscript ${{ github.event.inputs.msid }}v${{ github.event.inputs.versionManuscript || 1 }}"
          body:
            |
            ID: ${{ github.event.inputs.msid }}v${{ github.event.inputs.versionManuscript || 1 }}

            Please review and merge.
          token: ${{ env.GITHUB_TOKEN }}
      - name: Commit changes to existing branch (not master)
        if: github.ref != 'refs/heads/master'
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: action@github.com
          message: "Add pdf url to manuscript ${{ github.event.inputs.msid }}v${{ github.event.inputs.versionManuscript || 1 }} using workflow"
